# 21 April

In [9]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np

# Sample regression data
y_true = np.array([3.0, -0.5, 2.0, 7.0])
y_pred = np.array([2.5, 0.0, 2.0, 8.0])

# Calculate MSE, MAE, RMSE
mse = mean_squared_error(y_true, y_pred)
mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mse)

print(f"MSE: {mse}")
print(f"MAE: {mae}")
print(f"RMSE: {rmse}")

MSE: 0.375
MAE: 0.5
RMSE: 0.6123724356957945


In [10]:
# R-Squared Score
from sklearn.metrics import r2_score
import numpy as np

y_true = np.array([3.0, -0.5, 2.0, 7.0])
y_pred = np.array([2.5, 0.0, 2.0, 8.0])

r2 = r2_score(y_true, y_pred)
print(f"R-Squared Score: {r2}")

R-Squared Score: 0.9486081370449679


In [11]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
import numpy as np

y_true = np.array([0, 1, 1, 0, 1, 0, 1, 1])
y_pred = np.array([0, 0, 1, 0, 1, 1, 1, 0])

cm = confusion_matrix(y_true, y_pred)

print(f"Confusion Matrix: {cm}")

Confusion Matrix: [[2 1]
 [2 3]]


In [15]:
# Accuracy Score
from sklearn.metrics import accuracy_score
import numpy as np

y_true = np.array([0, 1, 1, 0, 1, 0, 1, 1])
y_pred = np.array([0, 0, 1, 0, 1, 1, 1, 0])

acc_score = accuracy_score(y_true, y_pred)
print(f"Accuracy Score: {acc_score}")

Accuracy Score: 0.625


In [17]:
# Precision Score
from sklearn.metrics import precision_score
import numpy as np

y_true = np.array([0, 1, 1, 0, 1, 0, 1, 1])
y_pred = np.array([0, 0, 1, 0, 1, 1, 1, 0])

prec_score = precision_score(y_true, y_pred)

print(f"Precision Score: {prec_score}")

Precision Score: 0.75


In [19]:
# Recall Score
from sklearn.metrics import recall_score
import numpy as np

y_true = np.array([0, 1, 1, 0, 1, 0, 1, 1])
y_pred = np.array([0, 0, 1, 0, 1, 1, 1, 0])

rec_score = recall_score(y_true, y_pred)

print(f"Recall Score: {rec_score}")

Recall Score: 0.6


In [21]:
# F1 Score
from sklearn.metrics import f1_score
import numpy as np

y_true = np.array([0, 1, 1, 0, 1, 0, 1, 1])
y_pred = np.array([0, 0, 1, 0, 1, 1, 1, 0])

f1 = f1_score(y_true, y_pred)

print(f"F1 Score: {f1}")

F1 Score: 0.6666666666666666


In [22]:
from sklearn import datasets

iris = datasets.load_iris()

print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.